RUNTIME ERROR: xxx
-------------------------------------------------
	testdata/error_from_func:1:25-32	function <foo>

local foo = function(x) error x; foo("xxx")

-------------------------------------------------
	testdata/error_from_func:1:34-44	$

local foo = function(x) error x; foo("xxx")

-------------------------------------------------
	During evaluation	


