{ [error "xxx"]: 42 for x in [1] }
